import type { PackingList, TripInput } from "./schemas";

export function toMarkdown(input: TripInput, result: PackingList): string {
  const lines: string[] = [];
  lines.push(`# Packing List: ${input.destination}`);
  lines.push("");
  lines.push(
    `**${input.days} days** · ${input.month} · ${input.tripType} · ${input.transport}`
  );
  if (input.extras) lines.push(`> Special needs: ${input.extras}`);
  lines.push("");
  lines.push(result.summary);
  lines.push("");
  for (const cat of result.categories) {
    lines.push(`## ${cat.name}`);
    if (cat.items.length === 0) {
      lines.push("_Nothing required._");
    } else {
      for (const item of cat.items) {
        const qty = item.quantity ? ` (${item.quantity})` : "";
        const note = item.note ? ` — ${item.note}` : "";
        lines.push(`- [ ] ${item.name}${qty}${note}`);
      }
    }
    lines.push("");
  }
  lines.push("---");
  lines.push(`Generated by Pack Planner · ${new Date().toLocaleString()}`);
  return lines.join("\n");
}

export function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function downloadPdfFromElement(
  el: HTMLElement,
  filename: string
) {
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import("html2canvas"),
    import("jspdf"),
  ]);
  const canvas = await html2canvas(el, {
    scale: 2,
    backgroundColor: getComputedStyle(document.body).backgroundColor || "#ffffff",
    useCORS: true,
  });
  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const ratio = canvas.width / canvas.height;
  const imgWidth = pageWidth - 40;
  const imgHeight = imgWidth / ratio;

  let y = 20;
  let remainingHeight = imgHeight;
  // Simple single-page; if too tall, slice into multiple pages.
  if (imgHeight <= pageHeight - 40) {
    pdf.addImage(imgData, "PNG", 20, y, imgWidth, imgHeight);
  } else {
    // Multi-page slicing
    const pageCanvasHeightPx = ((pageHeight - 40) / imgWidth) * canvas.width;
    let sY = 0;
    while (sY < canvas.height) {
      const sliceCanvas = document.createElement("canvas");
      sliceCanvas.width = canvas.width;
      sliceCanvas.height = Math.min(pageCanvasHeightPx, canvas.height - sY);
      const ctx = sliceCanvas.getContext("2d");
      if (!ctx) break;
      ctx.drawImage(
        canvas,
        0,
        sY,
        canvas.width,
        sliceCanvas.height,
        0,
        0,
        canvas.width,
        sliceCanvas.height
      );
      const sliceData = sliceCanvas.toDataURL("image/png");
      const sliceHeightPt = (sliceCanvas.height / canvas.width) * imgWidth;
      pdf.addImage(sliceData, "PNG", 20, 20, imgWidth, sliceHeightPt);
      sY += sliceCanvas.height;
      if (sY < canvas.height) pdf.addPage();
    }
  }

  pdf.save(filename);
  void remainingHeight;
  void y;
}
