import type { PackingList, TripInput } from "./schemas";

export function toMarkdown(input: TripInput, result: PackingList): string {
  const lines: string[] = [];
  lines.push(`# Packing List: ${input.destination}`);
  lines.push("");
  lines.push(
    `**${input.days} days** · ${input.month} · ${input.tripType} · ${input.transport}`
  );
  if (input.extras) lines.push(`> Special needs: ${input.extras}`);
  lines.push("");
  lines.push(result.summary);
  lines.push("");
  for (const cat of result.categories) {
    lines.push(`## ${cat.name}`);
    if (cat.items.length === 0) {
      lines.push("_Nothing required._");
    } else {
      for (const item of cat.items) {
        const qty = item.quantity ? ` (${item.quantity})` : "";
        const note = item.note ? ` — ${item.note}` : "";
        lines.push(`- [ ] ${item.name}${qty}${note}`);
      }
    }
    lines.push("");
  }
  lines.push("---");
  lines.push(`Generated by Pack Planner · ${new Date().toLocaleString()}`);
  return lines.join("\n");
}

export function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function downloadPdfFromElement(
  el: HTMLElement,
  filename: string
) {
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import("html2canvas"),
    import("jspdf"),
  ]);
  const canvas = await html2canvas(el, {
    scale: 2,
    backgroundColor: "#ffffff",
    useCORS: true,
    onclone: (doc) => {
      const root = doc.documentElement;
      root.style.setProperty("--background", "#ffffff");
      root.style.setProperty("--foreground", "#0f172a");
      root.style.setProperty("--card", "#ffffff");
      root.style.setProperty("--card-foreground", "#0f172a");
      root.style.setProperty("--popover", "#ffffff");
      root.style.setProperty("--popover-foreground", "#0f172a");
      root.style.setProperty("--primary", "#2563eb");
      root.style.setProperty("--primary-foreground", "#ffffff");
      root.style.setProperty("--secondary", "#fbbf24");
      root.style.setProperty("--secondary-foreground", "#0f172a");
      root.style.setProperty("--muted", "#f1f5f9");
      root.style.setProperty("--muted-foreground", "#475569");
      root.style.setProperty("--accent", "#ec4899");
      root.style.setProperty("--accent-foreground", "#ffffff");
      root.style.setProperty("--destructive", "#ef4444");
      root.style.setProperty("--border", "#e5e7eb");
      root.style.setProperty("--input", "#f8fafc");
      root.style.setProperty("--ring", "#2563eb");
      root.style.setProperty("--chart-1", "#2563eb");
      root.style.setProperty("--chart-2", "#1d4ed8");
      root.style.setProperty("--chart-3", "#4338ca");
      root.style.setProperty("--chart-4", "#7c3aed");
      root.style.setProperty("--chart-5", "#c026d3");
      root.style.setProperty("--sidebar", "#f8fafc");
      root.style.setProperty("--sidebar-foreground", "#0f172a");
      root.style.setProperty("--sidebar-primary", "#2563eb");
      root.style.setProperty("--sidebar-primary-foreground", "#ffffff");
      root.style.setProperty("--sidebar-accent", "#c026d3");
      root.style.setProperty("--sidebar-accent-foreground", "#ffffff");
      root.style.setProperty("--sidebar-border", "#e5e7eb");
      root.style.setProperty("--sidebar-ring", "#2563eb");
      doc.body.style.backgroundColor = "#ffffff";
      const style = doc.createElement("style");
      style.textContent = `
        .glass { background-color: rgba(255, 255, 255, 0.85) !important; background-image: none !important; }
        .bg-aurora { background-image: none !important; }
        .text-gradient-brand { background: none !important; color: inherit !important; }
      `;
      doc.head.appendChild(style);
    },
  });
  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const ratio = canvas.width / canvas.height;
  const imgWidth = pageWidth - 40;
  const imgHeight = imgWidth / ratio;

  let y = 20;
  let remainingHeight = imgHeight;
  // Simple single-page; if too tall, slice into multiple pages.
  if (imgHeight <= pageHeight - 40) {
    pdf.addImage(imgData, "PNG", 20, y, imgWidth, imgHeight);
  } else {
    // Multi-page slicing
    const pageCanvasHeightPx = ((pageHeight - 40) / imgWidth) * canvas.width;
    let sY = 0;
    while (sY < canvas.height) {
      const sliceCanvas = document.createElement("canvas");
      sliceCanvas.width = canvas.width;
      sliceCanvas.height = Math.min(pageCanvasHeightPx, canvas.height - sY);
      const ctx = sliceCanvas.getContext("2d");
      if (!ctx) break;
      ctx.drawImage(
        canvas,
        0,
        sY,
        canvas.width,
        sliceCanvas.height,
        0,
        0,
        canvas.width,
        sliceCanvas.height
      );
      const sliceData = sliceCanvas.toDataURL("image/png");
      const sliceHeightPt = (sliceCanvas.height / canvas.width) * imgWidth;
      pdf.addImage(sliceData, "PNG", 20, 20, imgWidth, sliceHeightPt);
      sY += sliceCanvas.height;
      if (sY < canvas.height) pdf.addPage();
    }
  }

  pdf.save(filename);
  void remainingHeight;
  void y;
}
